---
  mappings:
    # old_name: new_name
    node_bcache_cache_read_races: node_bcache_cache_read_races_total

    node_buddyinfo_count: node_buddyinfo_blocks

    node_boot_time: node_boot_time_seconds
    node_context_switches: node_context_switches_total
    node_forks: node_forks_total
    node_intr: node_intr_total

    node_disk_bytes_read: node_disk_read_bytes_total
    node_disk_bytes_written: node_disk_written_bytes_total

    node_disk_io_time_weighted: node_disk_io_time_weighted_seconds_total
    node_disk_reads_completed: node_disk_reads_completed_total
    node_disk_reads_merged: node_disk_reads_merged_total
    node_disk_writes_completed: node_disk_writes_completed_total
    node_disk_writes_merged: node_disk_writes_merged_total

    node_filesystem_free: node_filesystem_free_bytes
    node_filesystem_avail: node_filesystem_avail_bytes
    node_filesystem_size: node_filesystem_size_bytes

    node_infiniband_port_data_received_bytes: node_infiniband_port_data_received_bytes_total
    node_infiniband_port_data_transmitted_bytes: node_infiniband_port_data_transmitted_bytes_total

    node_interrupts: node_interrupts_total

    node_memory_Active: node_memory_Active_bytes
    node_memory_Active_anon: node_memory_Active_anon_bytes
    node_memory_Active_file: node_memory_Active_file_bytes
    node_memory_AnonHugePages: node_memory_AnonHugePages_bytes
    node_memory_AnonPages: node_memory_AnonPages_bytes
    node_memory_Bounce: node_memory_Bounce_bytes
    node_memory_Buffers: node_memory_Buffers_bytes
    node_memory_Cached: node_memory_Cached_bytes
    node_memory_CommitLimit: node_memory_CommitLimit_bytes
    node_memory_Committed_AS: node_memory_Committed_AS_bytes
    node_memory_DirectMap2M: node_memory_DirectMap2M_bytes
    node_memory_DirectMap4k: node_memory_DirectMap4k_bytes
    node_memory_Dirty: node_memory_Dirty_bytes
    node_memory_HardwareCorrupted: node_memory_HardwareCorrupted_bytes
    node_memory_Hugepagesize: node_memory_Hugepagesize_bytes
    node_memory_Inactive: node_memory_Inactive_bytes
    node_memory_Inactive_anon: node_memory_Inactive_anon_bytes
    node_memory_Inactive_file: node_memory_Inactive_file_bytes
    node_memory_KernelStack: node_memory_KernelStack_bytes
    node_memory_Mapped: node_memory_Mapped_bytes
    node_memory_MemAvailable: node_memory_MemAvailable_bytes
    node_memory_MemFree: node_memory_MemFree_bytes
    node_memory_MemTotal: node_memory_MemTotal_bytes
    node_memory_Mlocked: node_memory_Mlocked_bytes
    node_memory_NFS_Unstable: node_memory_NFS_Unstable_bytes
    node_memory_PageTables: node_memory_PageTables_bytes
    node_memory_Shmem: node_memory_Shmem_bytes
    node_memory_Slab: node_memory_Slab_bytes
    node_memory_SReclaimable: node_memory_SReclaimable_bytes
    node_memory_SUnreclaim: node_memory_SUnreclaim_bytes
    node_memory_SwapCached: node_memory_SwapCached_bytes
    node_memory_SwapFree: node_memory_SwapFree_bytes
    node_memory_SwapTotal: node_memory_SwapTotal_bytes
    node_memory_Unevictable: node_memory_Unevictable_bytes
    node_memory_VmallocChunk: node_memory_VmallocChunk_bytes
    node_memory_VmallocTotal: node_memory_VmallocTotal_bytes
    node_memory_VmallocUsed: node_memory_VmallocUsed_bytes
    node_memory_Writeback: node_memory_Writeback_bytes
    node_memory_WritebackTmp: node_memory_WritebackTmp_bytes
    node_memory_DirectMap1G: node_memory_DirectMap1G_bytes

    node_network_receive_bytes: node_network_receive_bytes_total
    node_network_receive_compressed: node_network_receive_compressed_total
    node_network_receive_drop: node_network_receive_drop_total
    node_network_receive_errs: node_network_receive_errs_total
    node_network_receive_fifo: node_network_receive_fifo_total
    node_network_receive_frame: node_network_receive_frame_total
    node_network_receive_multicast: node_network_receive_multicast_total
    node_network_receive_packets: node_network_receive_packets_total
    node_network_transmit_bytes: node_network_transmit_bytes_total
    node_network_transmit_compressed: node_network_transmit_compressed_total
    node_network_transmit_drop: node_network_transmit_drop_total
    node_network_transmit_errs: node_network_transmit_errs_total
    node_network_transmit_fifo: node_network_transmit_fifo_total
    node_network_transmit_frame: node_network_transmit_frame_total
    node_network_transmit_multicast: node_network_transmit_multicast_total
    node_network_transmit_packets: node_network_transmit_packets_total

    node_nfs_net_connections: node_nfs_connections_total
    node_nfs_net_reads: node_nfs_packets_total
    node_nfs_rpc_authentication_refreshes: node_nfs_rpc_authentication_refreshes_total
    node_nfs_rpc_operations: node_nfs_rpcs_total
    node_nfs_rpc_retransmissions: node_nfs_rpc_retransmissions_total

    node_textfile_mtime: node_textfile_mtime_seconds

  scalings:
    - old: node_disk_io_time_ms
      new: node_disk_io_time_seconds_total
      factor: ' * 1000'
    - old: node_disk_read_time_ms
      new: node_disk_read_time_seconds_total
      factor: ' * 1000'
    - old: node_disk_write_time_ms
      new: node_disk_write_time_seconds_total
      factor: ' * 1000'

  query_parameters: # TODO
    - old: node_cpu
      # For param mode:guest, new metric name is "node_cpu_guest_seconds_total" and mode is user
      # For param mode:guest_nice, new metric name is "node_cpu_guest_seconds_total" and mode is nice
      # For param cpu, "cpu" is replaced out of the value leaving the index, e.g. 'cpu0'.replace('cpu', '')
      new:
        - node_cpu_guest_seconds_total
        - node_cpu_seconds_total
    - old: node_nfs_procedures
      # Param procedure is renamed to method
      # Param version is renamed to proto
      new: node_nfs_requests_total

# https://prometheus.io/docs/prometheus/latest/querying/functions/
  functions:
    - abs
    - absent
    - ceil
    - changes
    - clamp_max
    - clamp_min
    - day_of_month
    - day_of_week
    - days_in_month
    - delta
    - deriv
    - exp
    - floor
    - histogram_quantile
    - holt_winters
    - hour
    - idelta
    - increase
    - irate
    - label_join
    - label_replace
    - ln
    - log2
    - log10
    - minute
    - month
    - predict_linear
    - rate
    - resets
    - round
    - scalar
    - sort
    - sort_desc
    - sqrt
    - time
    - timestamp
    - vector
    - year
    - avg_over_time
    - min_over_time
    - max_over_time
    - sum_over_time
    - count_over_time
    - quantile_over_time
    - stddev_over_time
    - stdvar_over_time

# https://prometheus.io/docs/prometheus/latest/querying/operators/#aggregation-operators
  operators:
    - sum
    - min
    - max
    - avg
    - stddev
    - stdvar
    - count
    - count_values
    - bottomk
    - topk
    - quantile

  excluded_dashboards:
    - 000000403
    - 000000425
    - 000000424
    - 000000414

  grafana_host: 'https://grafana.wikimedia.org'
